### PR TITLE
Added GENERATOR variable to manage a make package target for deb binary pacakges

### PR DESCRIPTION
**Pull request by anaselli**
It can build deb, rpm packages or any valid cmake generators, to use it run "cmake -DGENERATE=DEB" for instance.
This change is related to https://github.com/libyui/libyui/pull/87, since here the  CMakeLists.txt is not built by using libyui buildtools

### CODE REVIEW

**Comment by jreidinger** [comment]
What is advantage of this way generating packages before using for example (buildservice)[http://openbuildservice.org/] and build there for more platforms?  It looks like very limited and not following convinces. But of course if it is needed only for developer testing, then it make sense.

**Comment by kobliha** [comment]
@jreidinger Do you have a link for `How SUSE usually does it`? Or is the common approach, you are mentioning, documented somewhere?

**Comment by jreidinger** [comment]
@kobliha it is not suse specific, I just would like to get use case for this change. If goal is to distribute deb packages, then I think there is better ways then autogenerated deb package by cmake. If it is just for testing code on debian with having it handled by packager, then it make sense for me.

**Comment by anaselli** [comment]
The aim is to have a package available for developer that is compatible with his distro.
libyui is (or was) not available in debian/ubuntu and i wanted to show the evidence of how simple was to import manatools in debian (removing the rpm package manager, i.e. rpmdragora)

**Comment by jreidinger** [comment]
OK, it doesn't hurt to have such ability, so lets merge it.
Thanks

**Pull request merged**
